spring:
  application:
    name: product
  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mariadb://localhost:3306/product
    username: root
    password: sonnk7
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  liquibase:
    enabled: false
cloudinary:
  cloud-name: diwlrxoqc
  api-key: 748661693984332
  api-secret: hZWJ1cq7OUgEWUw8x8ewA0ub-0c
logging:
  level:
    root: INFO
    com.sonnk.product: DEBUG