# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODc0NTU5NThlNzlkYzE3Y2MzNDBkMDgzZTJiNGYyMmU2YzZkNmNmYmZkNWQ4Mzk3NzgyZTA3NDQ4NTA4ODYyYjM3ZmQwMTM3ZGFmNGUzOGM0Zjg2ZWMzZmQ5MmI1MWI3MWQwZjM2ODU2MTQwYjRmNmYwNmIyZTg1YzRhMGVkOTY=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
